services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    # environment:
    #   - BLOB_CONN_STR=${BLOB_CONN_STR} 
    #   - MONGODB_URL=mongodb+srv://azureuser:iaisolution%40123@mongotest01.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
    env_file:
      - ./backend/.env

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
